#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Leakage-safe model training from completed NEW_LOTO7 backtest rows.

Future-leak prevention policy:
1. Backtest rows must be generated by walk-forward validation.
   - For target draw index i, prediction uses draws[:i] only.
   - Actual result draws[i] is used only for scoring after prediction.
2. This script does not create future labels.
3. Latest prediction target is the next draw after the latest known draw in loto7.csv.
   The target result is not present, so it cannot be used for training.
4. Training source is completed historical prediction-vs-result rows only.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import List

from loto7_advanced_optimizer import (
    CLUSTER_CSV,
    META_CLASSIFIER_JSON,
    NEXTGEN_META6_JSON,
    NEXTGEN_SHAP_JSON,
    build_hit_structure_clusters,
    train_meta_classifier,
)


def _count_rows(path: str) -> int:
    p = Path(path)
    if not p.exists() or p.stat().st_size == 0:
        return 0
    with p.open("r", encoding="utf-8-sig", newline="") as f:
        return sum(1 for _ in csv.DictReader(f))


def _latest_detail_date(path: str) -> str:
    p = Path(path)
    if not p.exists() or p.stat().st_size == 0:
        return ""
    dates: List[str] = []
    with p.open("r", encoding="utf-8-sig", newline="") as f:
        for row in csv.DictReader(f):
            d = str(row.get("抽せん日", ""))
            if d:
                dates.append(d)
    return max(dates) if dates else ""


def main() -> int:
    parser = argparse.ArgumentParser(description="Train leakage-safe model artifacts from completed backtest detail rows.")
    parser.add_argument("--detail-csv", default="loto7_backtest_detail.csv")
    parser.add_argument("--cluster-csv", default=CLUSTER_CSV)
    parser.add_argument("--meta-json", default=META_CLASSIFIER_JSON)
    parser.add_argument("--meta6-json", default=NEXTGEN_META6_JSON)
    parser.add_argument("--shap-json", default=NEXTGEN_SHAP_JSON)
    args = parser.parse_args()

    rows = _count_rows(args.detail_csv)
    if rows <= 0:
        print(f"[SKIP] no completed backtest detail rows: {args.detail_csv}")
        return 0

    latest_date = _latest_detail_date(args.detail_csv)
    print("=== Leakage-safe training from completed backtest rows ===")
    print(f"detail_csv: {args.detail_csv}")
    print(f"training_rows: {rows}")
    print(f"latest_training_result_date: {latest_date}")

    build_hit_structure_clusters(args.detail_csv, args.cluster_csv)
    train_meta_classifier(args.detail_csv, args.meta_json)

    try:
        from loto7_nextgen_models import shap_feature_selection, train_meta6_classifier

        train_meta6_classifier(args.detail_csv, args.meta6_json)
        shap_feature_selection(args.detail_csv, args.shap_json)
    except Exception as exc:
        print(f"[WARN] optional nextgen training skipped: {exc}")

    print("[OK] model artifacts updated from historical backtest results only.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
